name: Node.js CI

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci

  build:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run build

  lint:
    needs: setup 
    runs-on: ubuntu-latest
    steps:
      - run: npm run lint

  test:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - run: npm run test -- --watch=false --browsers=ChromeHeadless
