name: Node.js CI

on:
  pull_request:
    branches:
      - main
      - develop
jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: yarn install --frozen-lockfile
      - run: yarn build:prod @klippa/ngx-async-template
